### ISSUE TITLE
Game crashes on meteor spawning

### ISSUE THREAD

**Issue by Craluminum2413** [TaskaRaine/Meteoric-Expansion#1]
**Game Version:** 1.15.0-pre.3
**Mod Version:** 1.0.4

```
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.Entities.EntityProperties.Attributes'.
   at MeteoricExpansion.EntityMeteor.Initialize(EntityProperties properties, ICoreAPI api, Int64 InChunkIndex3d)
   at Vintagestory.Server.ServerMain.SpawnEntity(Entity entity, EntityProperties type)
   at Vintagestory.Server.ServerMain.SpawnEntity(Entity entity)
   at MeteoricExpansion.MeteorSpawner.onSpawnerTick(Single deltaTime)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Server.CoreServerEventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Server.ServerMain.Process()
```

**Comment by TaskaRaine** [comment]
This is due to some changes to Vintage Story namespaces with version 1.15. I'll have updates for 1.15 ready that tackles these crashes when it launches.

Thanks for the report ^.^
