### ISSUE TITLE
Bricked Save

### ISSUE THREAD

**Issue by greyDragon0** [TaskaRaine/Meteoric-Expansion#12]
Meteor crash landed in my fuit tree garden and it keeps crashing on loading of the save

**Comment by TaskaRaine** [comment]
This is more likely an issue with how fruit trees handle parts of the tree being removed, and not specifically Meteoric Expansion. I could glean some useful insight if you could provide your crash log. 

There is a way to enter a 'repair mode' with Vintage Story that should help you recover your save. In the list of worlds where you would normally load your world, there is a pencil button alongside the world selection boxes. Click that, then 'Run in repair mode'. If I recall correctly, this loads the world without block entities, one or more of which are likely causing you grief. This should allow you to enter the world and delete all the trees affected by the meteor and the meteor itself. Save the game and try to load normally.

**Comment by greyDragon0** [comment]
Thx for response.My save have more than 130 hours played, always keeping backup. Lost like about 2-3 hours of gameplay.
But oh well. Tried recovery mode like 4 times but it keeps crashing same way as before. Here log

Game Version: v1.18.15 (Stable)
07.01.2024 19:19:10: Critical error occurred
Loaded Mods: aculinaryartillery@1.0.15, backpackpack@1.0.3, betterruins@0.2.4, bettertraders@0.0.2, immersivecorpsedrop@1.0.1, justmoreruins@0.9.2, meteoricexpansion@1.2.4, millwright@1.1.1, MoreTorchHolders@1.0.0, primitivesurvival@3.3.0, RelightTorches@1.0.0, spyglass@0.4.7, locustmod@2.3.6, game@1.18.15, weaponpackalphaunoff@1.4.0, alchemy@1.6.21, carryon@1.6.1, commonlib@2.2.0, expandedfoods@1.6.8, farmlanddropssoil@1.4.0, fromgoldencombs@1.4.25, hudclock@3.4.0, medievalexpansion@3.11.1, mouse4and5@1.0.0, petai@1.8.1, prospectorinfo@4.3.0, stillnecessaries@1.0.1, th3dungeon@0.2.0, usefulstuff17@1.2.0, vtpp@1.1.0, creative@1.18.15, survival@1.18.15, workbenchexpansion@1.6.3, metalrecovery@0.1.19-pre.1, bullseye@2.5.1, extraoverlays@1.3.1, feverstonehorses@1.5.5, helvehammerext@1.5.2, stonequarry@3.1.7, tpnet@1.13.2
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Vintagestory.GameContent.BlockFruitTreeBranch.OnBeforeRender(ICoreClientAPI capi, ItemStack itemstack, EnumItemRenderTarget target, ItemRenderInfo& renderinfo)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target, Single dt)
   at Vintagestory.Client.NoObf.RenderAPIGame.GetItemStackRenderInfo(ItemSlot inSlot, EnumItemRenderTarget target)
   at Vintagestory.GameContent.EntityItemRenderer.DoRender3DOpaque(Single dt, Boolean isShadowPass)
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnRenderOpaque3D_Patch0(SystemRenderEntities this, Single deltaTime)
   at Vintagestory.API.Client.DummyRenderer.OnRenderFrame(Single deltaTime, EnumRenderStage stage)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt)
   at Vintagestory.Client.ScreenManager.Render(Single dt)
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt)
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e)
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1()
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start)

**Comment by TaskaRaine** [comment]
I think my only option is to prevent the fruit trees from being destroyed. I can't do anything to fix whatever is happening within the fruit tree logic itself. I'll include this in the VS 1.19 compatibility update.

**Comment by greyDragon0** [comment]
Thanks
